name: E3ServerSettings
version: ${project.version}
main: ru.euj3ne.e3serversettings.E3ServerSettings
api-version: '1.21'
authors: [euj3ne]
description: ${project.description}
website: ${project.url}
depend: [ProtocolLib]
